# Generated by Django 5.1.3 on 2024-12-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_email_alter_book_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='text',
            new_name='date',
        ),
    ]
